### ISSUE TITLE
(BUG) Main window lockup when closing with the X button

### ISSUE THREAD

**Issue by BreakPoints** [BrokenSource/DepthFlow#33]
Closing the DepthFlow main window (launched from cli with 'main') using the windows topbar cross button in the top right will cause the window to become unresponsive. Closing the cli window will still close both even after the lockup.

Windows 11 23H2, Nvidia 4090 on latest drivers. DepthFlow v0.5.0

**Comment by Tremeschin** [comment]
If you mean launching from cli as in `double click -> prompt -> type main` instead of `.\depthflow.exe main`, then..

..yea, the scene doesn't hides/destroys itself after closing the window in any way currently, as we might reutilize it when managing it externally on some code. It's known in my part and why I've left the _"projects might not work as expected"_

A 'workaround' is to open a powershell where the binary is and run as `.\depthflow-*.exe (...)`, for now at least

I'll have to think more how to handle this, maybe having an exit hook on the cli to destroy objects could solve it, but then would need an external loop always recreating the depthflow scene in this case

or maybe just hiding the window does the trick, I'll experiment with it, thanks for the report mostly for awareness 👍🏻

**Comment by BreakPoints** [comment]
Yeah, that's exactly what I meant, a simple `double click the .exe -> main`.

Thanks for the workaround, it's pretty hard to fight my Windows born muscle memory! Also thanks for explaining, I know how annoying bug reports on known issues can be.

**Comment by Tremeschin** [comment]
haha, no problem @BreakPoints :), I'm pretty much full time now at this, and it's a valid bug 👍🏻 

I should've waited a bit more to iron out those issues, but the last release was a couple months old and was kinda needed

**Comment by BreakPoints** [comment]
Nice job, will let you know if it still happens
