### ISSUE TITLE
Severe Performance Degradation in GPU Rendering When Running FastAPI in Docker Compared to Host Environment

### ISSUE THREAD

**Issue by muhammad-ahmed-ghani** [BrokenSource/DepthFlow#52]
### 🔘 Operating system

Linux (Ubuntu-like)

### 🔘 Runtime enviroment

PyPI Wheels (pip, poetry, pdm, rye, etc)

### 🔘 Python version

Python 3.10

### 🔘 GPU Vendor

NVIDIA Desktop

### 🔘 Description

Hi @Tremeschin 
I'm experiencing a significant performance issue when running a FastAPI-based GPU rendering application inside a Docker container. When executing the same application directly on the host (without Docker), the rendering time is around **3 seconds**, but when running it inside Docker, it takes approximately **4 minutes**. 

#### **Environment Details:**
- **Host OS:** Ubuntu 22.04
- **Docker Base Image:** `nvidia/cuda:12.3.2-runtime-ubuntu22.04`
- **CUDA Version:** 12.3
- **Python Version:** 3.10
- **FastAPI Version:** Latest stable
- **GPU:** NVIDIA (using CUDA)
- **NVIDIA Driver Version:** Compatible with CUDA 12.3
- **Rendering Library:** Using `EGL` for headless GPU rendering

#### **Steps Taken So Far:**
1. **Installed NVIDIA Container Toolkit** to enable GPU acceleration in the container.
2. **Configured Dockerfile for Headless EGL Rendering**, including the installation of necessary libraries (`libglvnd`, `libegl`, `libgles2`).
3. **Tested with both Runtime and Development Variants of the CUDA Docker Image.** 
4. **Ensured Proper Usage of GPU Devices** inside the container using `--gpus "device=0"` to isolate the GPU.

Despite these efforts, the performance gap remains drastic, suggesting that there may be a configuration issue or some missing optimizations when using Docker for GPU-accelerated rendering.

#### **Dockerfile Configuration:**
Here's a simplified version of the current Dockerfile being used:

```dockerfile
FROM nvidia/cuda:12.3.2-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install necessary libraries
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
       build-essential \
       python3.10 \
       python3.10-dev \
       python3.10-venv \
       python3-pip \
       apt-utils \
       libglvnd-dev \
       libegl1-mesa \
       libgles2-mesa \
       libgl1-mesa-dri \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN python3.10 -m pip install --upgrade pip && pip install -r requirements.txt
COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
```

#### **Questions:**
1. **Is there a recommended approach for optimizing GPU performance inside Docker for this use case?** Are there specific configurations or environment variables for NVIDIA Docker that would help improve rendering times?
2. **Is there any known limitation with using EGL for headless rendering in Docker containers that could contribute to this issue?**
3. **Would switching to a different base image or configuring multi-stage builds be helpful in this case?**
4. **Are there additional libraries or tools that should be considered for efficient hardware-accelerated rendering in a Docker environment?**

Any guidance or advice on resolving this performance issue would be greatly appreciated. I am looking to achieve rendering times inside Docker that are comparable to the host execution.

Thank you!

**Comment by Tremeschin** [comment]
hello! in case you didn't figure it out before closing, here's some advices:

There's documentation on https://brokensrc.dev/get/docker/ (needs some cleanup) of what needs to happen for OpenGL acceleration to work when running locally in docker, but at first glance, considering yesterday's [findings](https://github.com/akatz-ai/ComfyUI-Depthflow-Nodes/issues/8#issuecomment-2409098774), you seem to be missing a `10_nvidia.json` icd loader file and the `libglvnd0` package in your dockerfile 🤔 

Instead of this manual work you could start with the `nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04` image and the nvidia should pop up; if it's `llvmpipe` then it's using CPU rendering and indeed performances will be abysmal 👀

I'm half afraid `--gpus=all` is needed instead of just device 0, I think it also enables `graphics,compute,video` etc. capabilities for the containers in nvidia's toolkit, but it could be a env var inside it I guess :)

I can get it all working (+cuda) with either a `ubuntu:22.04` image or the above, I didn't need any of `nvidia/cuda*` images though, so here's two examples that works for me:

### Non-nvidia/glvnd base images

```dockerfile
FROM ubuntu:22.04
WORKDIR /App

# Base requirements
RUN apt update && apt install -y python3 python3-pip python-is-python3 curl
RUN pip install torch==2.4.1 --index-url https://download.pytorch.org/whl/cu121
RUN pip install transformers

# Fixme: Why BtbN FFmpeg binaries "are faster" than 'apt install ffmpeg' one?
ARG FFMPEG_FLAVOR="ffmpeg-master-latest-linux64-gpl"
ARG FFMPEG_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${FFMPEG_FLAVOR}.tar.xz"
RUN curl -L ${FFMPEG_URL} | tar -xJ --strip-components=2 --exclude="doc" --exclude="man" -C /usr/local/bin

# libEGL / nvidia
RUN apt install -y libegl1-mesa libglvnd-dev libglvnd0
RUN mkdir -p /usr/share/glvnd/egl_vendor.d
RUN echo '{"file_format_version":"1.0.0","ICD":{"library_path":"/usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0"}}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json
ENV NVIDIA_DRIVER_CAPABILITIES="all"
ENV NVIDIA_VISIBLE_DEVICES="all"

# DepthFlow stuff
RUN python -m pip install depthflow==0.7.1
ENV WINDOW_BACKEND="headless"
ENV DOCKER_RUNTIME="1"

# Cache estimator model
RUN depthflow load-model
CMD depthflow main -r
```

### With nvidia/glvnd base image

```dockerfile
FROM nvidia/opengl:1.2-glvnd-runtime-ubuntu22.04
WORKDIR /App

# Base requirements
RUN apt update && apt install -y python3 python3-pip python-is-python3 curl
RUN pip install torch==2.4.1 --index-url https://download.pytorch.org/whl/cu121
RUN pip install transformers

# Fixme: Why BtbN FFmpeg binaries "are faster" than 'apt install ffmpeg' one?
ARG FFMPEG_FLAVOR="ffmpeg-master-latest-linux64-gpl"
ARG FFMPEG_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${FFMPEG_FLAVOR}.tar.xz"
RUN curl -L ${FFMPEG_URL} | tar -xJ --strip-components=2 --exclude="doc" --exclude="man" -C /usr/local/bin

# libEGL / nvidia
ENV NVIDIA_DRIVER_CAPABILITIES="all"
ENV NVIDIA_VISIBLE_DEVICES="all"

# DepthFlow stuff
RUN python -m pip install depthflow==0.7.1
ENV WINDOW_BACKEND="headless"
ENV DOCKER_RUNTIME="1"

# Cache estimator model
RUN depthflow load-model
CMD depthflow main -r
```

<hr>

Ideally we'd just `apt install ffmpeg` but I don't know why encoding speeds are much worse with it than downloading a btbn release, it's like, 350 fps vs 150 fps for a static 1080p video

My nvidia card shows up and is used on both examples running locally!, though with [`docker-compose`](https://github.com/BrokenSource/BrokenSource/blob/main/docker-compose.yml). Sidenote, if you're on WSL do also map a `/usr/lib/wsl:/usr/lib/wsl` volume, or it won't work 👍🏻

**Comment by muhammad-ahmed-ghani** [comment]
Thanks man it does work faster by using btbn release instead of clean ffmpeg.
